### ISSUE TITLE
Notes not managed

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#44]
0.90
Use Notes on a genericobject types. But no 'Notes' tab appear in the object instance form

**Comment by btry** [comment]
ready to test

**Comment by blerohellec** [comment]
Not better. I still don't have a 'Notes' tab.

**Comment by btry** [comment]
I forgot to mention, access to notes is not (yet) enabled by default. 

Edit your profile and tick the two related rights.

**Comment by blerohellec** [comment]
In profiles, tab 'GenericObjects' or tab Profiles of my object type, I don't have any right related to Notes

**Comment by btry** [comment]
Edit your generic object, and check "use notes". I think it is not checked.

**Comment by blerohellec** [comment]
Which branch should I use ? Master, Wip ?
I'm testing with GLPI 0.90.

**Comment by btry** [comment]
use the branck master. I'll keep WIP-notes for a while if some other related tweaks are needed

**Comment by blerohellec** [comment]
OK : master branch.
Still not better : 'Use notes' is ticked at the object type level.

**Comment by btry** [comment]
I just pushed a small change for better comfort : notes rights are enabled by default now. Maybe this will make things easier for most people.

The checkbox "use notes" should enable GLPI's notepad management. However notepad is useable depending on the rights on a current profile. Both of them must be enabled.

Maybe there is something wrong if the type has been upgraded despite my efforts to migrate the notes. Can you try with a new type ?

**Comment by blerohellec** [comment]
'Use Notes' is ticked.
In db, rights is now 127 by default, from the creation of the object type (even if Notes is not yet ticked) when it was 31 before.
But I still don't see any rights linked to the notes in the Profile tab of the object.
And I don't have any Notes tab in the object instance.

**Comment by btry** [comment]
Trying to reproduce, without failure. It is definitely working, even after a reinstall of the plugin.

Do you see a difference between your setup and my screenshots ?

![capture du 2015-09-18 17 17 33](https://cloud.githubusercontent.com/assets/14139801/9963067/6db2bac0-5e29-11e5-8432-c7c42cc5e055.png)

![capture du 2015-09-18 17 19 09](https://cloud.githubusercontent.com/assets/14139801/9963069/7255a0c4-5e29-11e5-9559-fb409c4ac585.png)

![capture du 2015-09-18 17 20 31](https://cloud.githubusercontent.com/assets/14139801/9963098/97e4b1ae-5e29-11e5-8e23-22d27283ed17.png)

**Comment by blerohellec** [comment]
OK, I understand.
Since the beginning, I'm testing the master with GLPI 0.90, while you're .. with 0.85.
So, it works with GLPI 0.85 ... but not with 0.90

**Comment by btry** [comment]
This should be fixed now for GLPI 0.90.x as well

**Comment by blerohellec** [comment]
OK for 0.90 as well. Thx
