### ISSUE TITLE
Page not found from a GenericObject instance linked to a project

### ISSUE THREAD

**Issue by blerohellec** [TECLIB/genericobject#54]
0.85
I've added an instance of my GenericObject to a project.
In the items tab of the project, Clicking on the Name of the GenObj, I get an error
The requested URL /glpi085/plugins/genericobject/front/voiture.form.php was not found on this server.

The source files of a GenObj have been moved. Now in /files/_plugins..

**Comment by blerohellec** [comment]
Same with 'used items' tab of a user.
Check all.

**Comment by wawax** [comment]
This has been fixed in 0.90.
it's related to GLPi's core modifications

**Comment by blerohellec** [comment]
Indeed, it's better in 0.90.
But there's still an error when 'Use infocoms' = Yes, from tab 'Items' of a supplier.
And I can't test with Project, because I get the msg 'you don't have permissions' when I try to add an item to the project, whatever the itemtype is (Monitor, Software, GO...)

**Comment by btry** [comment]
If something in the plugin has been created to test it with projects, I'm interested to know if a logout / login cycle workarounds your rights issue.

**Comment by blerohellec** [comment]
Logout/login doesn't change anything

**Comment by wawax** [comment]
this is a GLPi issue. Fixed in 0.90 in commit https://github.com/glpi-project/glpi/commit/49429263d26865150cf487b63df018bf80089251

**Comment by blerohellec** [comment]
OK for infocoms/supplier in 0.90

**Comment by wawax** [comment]
thanks for your bug report Benoît.
